services:
  postgres:
    image: postgres:15
    container_name: codevoyage_postgres
    environment:
      POSTGRES_DB: code_voyage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 