services:
  - type: web
    name: codevoyage
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: BASE_URL
        value: https://codevoyage.onrender.com
    healthCheckPath: /health
    autoDeploy: true
